### ISSUE TITLE
이건 의도된건가요 아니면 실수인가요

### ISSUE THREAD

**Issue by ghost** [delta-kor/kakao-message-template#2]
src/components/MessageInfo.ts에는 KV가 있지만
dist/components/MessageInfo.js에는 KV가 없네요

src/components/MessageInfo.ts
        return {
            TP: this.type,
            ME: '최신기술',
            SNM: this.serviceName,
            SIC: this.serviceIcon,
            L: this.link.toJson(),
            SL: this.serviceLink.toJson(),
            FW: this.isForwardable,
            KV: this.IsVerified,
            VA: this.versionAndroid,
            VI: this.versionIphone,
            VW: this.versionWindows,
            VM: this.versionMac,
            SID: this.serviceID,
            DID: this.documentID
        };

dist/components/MessageInfo.js
        return {
            TP: this.type,
            ME: '최신기술',
            SNM: this.serviceName,
            SIC: this.serviceIcon,
            L: this.link.toJson(),
            SL: this.serviceLink.toJson(),
            VA: this.versionAndroid,
            VI: this.versionIphone,
            VW: this.versionWindows,
            VM: this.versionMac,
            SID: this.serviceID,
            DID: this.documentID,
        };

**Comment by txrx0031** [comment]
그냥 님이알아서 고치세요

**Comment by delta-kor** [comment]
``` isVerified ``` 와 ``` isForwardable ``` 은 [v1.0.4](https://www.npmjs.com/package/kakao-message-template/v/1.0.4) 에 추가되었습니다.
업데이트 부탁드립니다.
